### ISSUE TITLE
authselect is not idempotent

### ISSUE THREAD

**Issue by logicminds** [jcpunk/puppet-authselect#1]
Great module. Thanks for creating.

Just a small bug in the code where you compare the requested with the current.  You need to join the current_features so it becomes a string.  Without converting both to a string the comparison will always be true.

https://github.com/jcpunk/puppet-authselect/blob/main/manifests/init.pp#L44

**Comment by jcpunk** [comment]
I didn't expect github to auto close... Does the version I just pushed up look right to you?

If so, I'll put it on the forge....

**Comment by logicminds** [comment]
looks good to me

**Comment by jcpunk** [comment]
Should be on the forge now.
