### ISSUE TITLE
Not changing active profile

### ISSUE THREAD

**Issue by ic248** [jcpunk/puppet-authselect#4]
Hi,

There seems to be an issue where it isn't changing the active profile if the features are the same. We have a custom profile but want to leave it with the same features and it doesn't change to the new profile unless I add an additional feature.

By default we have the sssd profile with the with-mkhomedir feature. We want to use our custom sssd profile with the with-mkhomedir feature (we also have some logic for with mfa.

`            class {`
`                'authselect':`
`                    profile => 'custom/sssd',`
`                    profile_options => [ 'with-mkhomedir'],`
`                    require => File['/etc/authselect/custom/sssd'],`
`                    notify => Service['sshd'];`
`            }`

Please say if you require anything else.

Thanks
Ian

**Comment by jcpunk** [comment]
In theory I've fixed this with 1.0.1, let me know if that doesn't work.

**Comment by ic248** [comment]
@jcpunk that's fixed the issue, thanks for the quick response and fix
